---
name: "ci"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.1"

      - name: Build
        working-directory: src
        run: env GOOS=linux GOARCH=arm64 go build -o theme-manager cmd/theme-manager/main.go

      - name: Build Package Folder
        run: |
          mkdir "Theme Manager.pak"
          cp -R src/theme-manager resources/launch.sh README.md LICENSE resources/pak.json resources/minui-list resources/minui-presenter "Theme Manager.pak"

      - uses: actions/upload-artifact@v4
        with:
          name: "Theme Manager.pak"
          path: "Theme Manager.pak"
          if-no-files-found: error
          overwrite: true
